Remove `failure` crate
fortanix/rust-sgx pull request #564
Opened 2024-03-07 13:20 UTC by nshyrei

Changes all usages of `failure` crate (https://crates.io/crates/failure) across the project into `thiserror` (https://crates.io/crates/thiserror) and `anyhow` (https://crates.io/crates/anyhow). This change fixes vulnerability introduced by `failure` crate (https://rustsec.org/advisories/RUSTSEC-2020-0036)

2024-03-07 18:21 UTC, Taowyoo requested changes
The changes so far LGTM.

## Need to bump version number

But since this upgrade changes the function signatures, this will be a breaking change of all crates that are updated. **Which means you need to increase the minor version number of all crates you updated.**

## Concerns about changes and crate version before this breaking change

Before we merge this PR, I have to get clear about out release strategy about crates under `rust-sgx`.
If we want to have a version without this change but contains all changes before this PR and after last publish.
We need to publish new version of crates with new patch version if they only contain some version compatible changes.

Otherwise, we could just bump the minor versions in this PR.

2024-03-07 18:21 UTC, Taowyoo commented
@raoulstrackx @ssavvides What's your idea about ^^^

2024-03-08 17:47 UTC, Taowyoo requested changes

2024-03-08 17:47 UTC, Taowyoo commented on intel-sgx/aesm-client/Cargo.toml
> -version = "0.5.4"
Hi @nshyrei, please check https://semver.org/
The version convention is `MAJOR.MINOR.PATCH`. Bump the PATCH version does not represent the breaking change.

You need to at least bump the MINOR version.
This applies to all your other version update, too.

Could you fix them, thank you.

2024-03-08 17:48 UTC, Taowyoo commented on intel-sgx/aesm-client/Cargo.toml
> -version = "0.5.4"
You could use https://crates.io/crates/cargo-semver-checks to check if the version is file after you update them.

2024-03-10 20:10 UTC, nshyrei commented
@Taowyoo Please review last 2 commits

2024-03-11 16:30 UTC, Taowyoo requested changes
When using a new `MINOR` version, you should start with 0 for `MINOR`.
Note:
You could use this tool https://github.com/crate-ci/cargo-release to bump version in a more reliable way with command `argo release version minor` under root of each crate.

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/aesm-client/Cargo.toml
> +version = "0.6.4"
```suggestion
version = "0.6.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/dcap-provider/Cargo.toml
> +"report-test" = { version = "0.4.1", path = "../report-test" }
```suggestion
"report-test" = { version = "0.4.0", path = "../report-test" }
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/dcap-ql/Cargo.toml
> +version = "0.4.7"
```suggestion
version = "0.4.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/dcap-ql/Cargo.toml
> +report-test = { version = "0.4.1", path = "../report-test" }
```suggestion
report-test = { version = "0.4.0", path = "../report-test" }
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/dcap-retrieve-pckid/Cargo.toml
> +version = "0.2.3"
```suggestion
version = "0.2.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/dcap-retrieve-pckid/Cargo.toml
> +"report-test" = { version = "0.4.1", path = "../report-test" }
```suggestion
"report-test" = { version = "0.4.0", path = "../report-test" }
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/enclave-runner/Cargo.toml
> +version = "0.6.2"
```suggestion
version = "0.6.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/fortanix-sgx-tools/Cargo.toml
> +version = "0.6.1"
```suggestion
version = "0.6.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/report-test/Cargo.toml
> +version = "0.4.3"
```suggestion
version = "0.4.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/sgxs-loaders/Cargo.toml
> +version = "0.4.3"
```suggestion
version = "0.4.0"
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/sgxs-tools/Cargo.toml
> +"report-test" = { version = "0.4.1", path = "../report-test" }
```suggestion
"report-test" = { version = "0.4.0", path = "../report-test" }
```

2024-03-11 16:30 UTC, Taowyoo commented on intel-sgx/sgxs/Cargo.toml
> +version = "0.8.4"
```suggestion
version = "0.8.0"
```

2024-03-12 21:04 UTC, nshyrei commented
@Taowyoo Fixed, please review

2024-03-12 23:19 UTC, Taowyoo approved these changes
Good job! Thank you for working on this big upgrade!

2024-03-13 10:14 UTC, merged